pipeline:
  name: cronjon
  identifier: cronjon
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: execute
        identifier: execute
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          #!/bin/bash
                          echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
