environment:
  name: Dev
  identifier: Dev
  orgIdentifier: default
  projectIdentifier: default_project
  description: ""
  tags: {}
  type: PreProduction
  yaml: |
    environment:
      name: ""
      identifier: ""
      orgIdentifier: default
      projectIdentifier: default_project
      description: ""
      tags: {}
      type: ""
